import Head from 'next/head';

export default function Watch() {
	return (
		<>
			<Head>
				<title>Welcome To Celebration Church</title>
				{/* <meta name='description' content='Generated by create next app' /> */}
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<h1>Watch</h1>
		</>
	);
}
